### ISSUE TITLE
Monitoring tools

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Websocket#29]
Do we need these tools?
Do they exist?
Do we need to develop them?

/cc @marmotz and @Nasga

**Comment by Nasga** [comment]
At the moment we don't know what we have to monitor/dump/debug.

@marmotz : could you capture a http://www.sysdig.org trace when your web socket server is at 100% cpu ?

**Comment by marmotz** [comment]
Nop 'cause I do not have access to server (Yeah, I know, it's bad, blablabla)

**Comment by vonglasow** [comment]
Ok so @marmotz which part you can modify to know where we can try something. Have you access to log, or everything we can provide any more information.

**Comment by marmotz** [comment]
I have logs and I can modify all my code

**Comment by Hywan** [comment]
@marmotz Do you think this is still needed?

**Comment by marmotz** [comment]
Not for me

**Comment by Hywan** [comment]
@marmotz How did you solve your issue? Did you used a specific tool?

**Comment by marmotz** [comment]
I dropped doctrine
