### ISSUE TITLE
Where are the Tests?

### ISSUE THREAD

**Issue by harikt** [hoaproject/Websocket#36]
Hi, 

I was looking at http://wiki.hoa-project.net/projects:central:todo and noticed the tests are ticked. Am I missing to see where the Test resides ?

Thank you.

**Comment by Hywan** [comment]
Hello :-),

We use http://autobahn.ws/testsuite/. So it's external to Hoa. My goal is to mimic this test suite, or to recreate a new one, with Hoa\Test in long term. In short term, I would like to add scripts to automate this.

Help are welcomed!

**Comment by Hywan** [comment]
(I close the issue because I answered to your question but feel free to continue the discussion if needed!)

**Comment by harikt** [comment]
Thanks. I will look how I can contribute the same.

*Hari K T*

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt
