### ISSUE TITLE
How to deal with "disconnections" and "keep alive" stuff?

### ISSUE THREAD

**Issue by Oliboy50** [hoaproject/Websocket#42]
I didn't find, in the documentation (including "hack book"), a way to properly deal with client disconnections (network issues, etc.) and how to reconnect then.

Have you some additional informations to share about any disconnection related things?

Thanks for the good work!

**Comment by Hywan** [comment]
Hello :-),

Does this section help: http://hoa-project.net/En/Literature/Hack/Websocket.html#Listeners?

**Comment by Hywan** [comment]
(Take a look at the `close` listener).

**Comment by Hywan** [comment]
@Oliboy50 I am closing the issue since I consider it as resolved, but if you don't find the information you need, please feel free to reopen it or ask more help (on the same issue).

**Comment by tikagnus** [comment]
Hi guys. I have a question regarding close listener. Currently I am developing a iot device. I found an issue. When my iot device is disconnected from power source or internet connection, the close listener is not triggered. How should i handle this ? Thanks.

**Comment by Hywan** [comment]
@tikagnus Interesting use case. Could you open a new issue with a code example please?
