### ISSUE TITLE
Supports WSS (encrypted connection to run with HTTPS server)

### ISSUE THREAD

**Issue by Oliboy50** [hoaproject/Websocket#51]
What is the current state of the support of encrypted websocket connection?

What is the typical solution to run a websocket server wich is able to run an encrypted connection (which will be able to support a `new WebSocket('wss://my.host.com')` in javascript within a HTTPS connection) ?

Actually, the only thing I do in PHP is `run()` a Hoa WebsocketServer on `tcp://my.host.com:8889`.

**Comment by Hywan** [comment]
Please see https://github.com/hoaproject/Socket/pull/27 and https://github.com/hoaproject/Websocket/pull/47. This is a work in progress, almost done.
