### ISSUE TITLE
Query string parameters seem unsupported?

### ISSUE THREAD

**Issue by pietervogelaar** [hoaproject/Websocket#61]
It seems that query string parameters are unsupported. If I have a websocket URL like:

```
wss://br3-teapot.br.de/socket.io/?EIO=3&transport=websocket
```

I get an error

```
Handshake has failed, the server did not return a valid response.

Client:
    GET /socket.io/ HTTP/1.1
    ...
```

The query string is not in the HTTP request, but it is required. For example, if I test it on http://www.websocket.org/echo.html it works just fine with the complete url but not when the query string part is stripped.

This is a part of my code at the moment:

```
$socketClient = new SocketClient($url);
$webSocketClient = new WebSocketClient($socketClient);
```

What can I do to make this work?

**Comment by Hywan** [comment]
Hello :-),

Good idea and thank you for the feature request. I reckon you can try a PR by yourself (if you want to!). The `ws://` and `wss://` URI are transformed into `tcp://` and the line you might want to change could be https://github.com/hoaproject/Websocket/blob/ad7b3902528a2c1fe79154169c5037abd4311bec/Socket.php#L121. Do you want to try a PR?

**Comment by Hywan** [comment]
Without no answer from your end, I decided to make a PR :smiley:. The review should start very quickly and the merge will happen as fast as possible because this is a bug fix.

**Comment by Hywan** [comment]
A new snapshot has been released: https://github.com/hoaproject/Websocket/releases/tag/3.16.05.09. Thanks!
