### ISSUE TITLE
class  not found

### ISSUE THREAD

**Issue by viratayya** [hoaproject/Websocket#75]
i am following the same thing but still i am geting like this 

error:PHP Fatal error:  Class 'Hoa\Websocket\Server' not found
and even i checked in vendor ther is hoa folder present

**Comment by Hywan** [comment]
Hello 😃,

First, thanks for using Hoa!
Second, did you install `Hoa\Websocket` with Composer? If yes, did you include the `vendor/autoload.php` file? You may find this documentation useful https://hoa-project.net/Source.html#Dependency_manager_(Composer).

**Comment by Hywan** [comment]
I am closing this issue but feel free to re-open it if you are still experiencing a problem.
