### ISSUE TITLE
.

### ISSUE THREAD

**Issue by qwe356558603** [hoaproject/Websocket#83]

**Comment by qwe356558603** [comment]
![image](https://cloud.githubusercontent.com/assets/18321666/19846418/07b91bea-9f7a-11e6-9040-7d2db80bff29.png)

**Comment by Hywan** [comment]
Please @vonglasow, can you take this one?

**Comment by qwe356558603** [comment]
My front end can be normal operation
![image](https://cloud.githubusercontent.com/assets/18321666/19847610/1e1e2caa-9f83-11e6-993f-561c5aa5e277.png)
** but  My PHP client will timeout** @vonglasow 
![image](https://cloud.githubusercontent.com/assets/18321666/19847645/5935d5d6-9f83-11e6-85de-ddce0e304fa3.png)

**Comment by qwe356558603** [comment]
![image](https://cloud.githubusercontent.com/assets/18321666/19849448/5c171232-9f8e-11e6-9307-6107c2cfa5d7.png)

**Comment by Hywan** [comment]
Huh? Why did you close the issue?
