### ISSUE TITLE
I can only do it broadcast the current connection handshake，Refresh the browser node has changed, and know how to stay next time chat is this man

### ISSUE THREAD

**Issue by qwe356558603** [hoaproject/Websocket#84]
![image](https://cloud.githubusercontent.com/assets/18321666/19921056/263987be-a117-11e6-9daa-e6e069a5e93a.png)

**Comment by Hywan** [comment]
Please, can you do a correct issue? Set a correct title, set a correct description, and eventually, a script to reproduce. Thanks :-).
