### ISSUE TITLE
Connected clients on the server id

### ISSUE THREAD

**Issue by moirrer** [hoaproject/Websocket#85]
Is there a way to get a list/$buckets/bucket_id from all current connected clients?
Trying to do an implementation where once client #1 sends a message the server sends another to clients #2 and #3, so is not a broadcast and not to origin.
Can I accomplish that with HoaWebsocket?

**Comment by Hywan** [comment]
Hello @moirrer,

Yes, this is possible. You have the `broadcastIf` method, or you can grab all the connections at once with `$server->getConnection->getNodes()`.

**Comment by Hywan** [comment]
@moirrer Is your question answered?

**Comment by moirrer** [comment]
Yes, thanks so much.

**Comment by Hywan** [comment]
Thanks!
