### ISSUE TITLE
Send message to a specific Client from another place than $server->on('message'..)

### ISSUE THREAD

**Issue by tikagnus** [hoaproject/Websocket#93]
Hi guys. I'm working on a app that manage some IoT devices. Devices are WebSockets client connected to my app. 
Is there any method to send a message to a specific client from other place than $server->on(..) ? 
I want to send messages to device from my controller class.

```php
<?php
namespace App\Http\Controllers;
use App\Models\DeviceModel;

class DeviceController extends Controller
{
    public function turnOn(DeviceModel $deviceModel)
    {
        if($deviceModel->state == 'OFF'){
           $message = 'ON';
            ...
            Something::send(
                $deviceModel->websocketNodeId,
                $message
            );
            ...
        }
    }
}
```

Here I try to link client connection with a unique node instance.
```php
$ws->on('message', function (\Hoa\Event\Bucket $ev) {

    $message = json_decode($ev->getData()['message'] ?? '{}');
    $node  = $ev->getSource()->getConnection()->getCurrentNode();

    //assign client to a specific node, in my case, to a DeviceNode.

    if($node instanceof \Hoa\Websocket\Node && $message->deviceToken){

        $ev->getSource()->getConnection()->setNodeName(\App\TiCTRL\DeviceNode::class);
        $node = $ev->getSource()->getConnection()->getCurrentNode();

        $nodeId = $node->getId;

        $deviceModel = \App\Models\DeviceModel::updateNodeIdByTokenAndGet($message->deviceToken,$nodeId);

        $node->setDeviceModel($deviceModel);
    }

});
```

**Comment by Pierozi** [comment]
Hello @tikagnus 
The `Hoa\WebSocket` is event based. I recommend you to listen `open` connection and keep the `Hoa\WebSocket\Connection` object of the clients in your internal code.

Then on each of this Connection object, you are able to use `send` method as you which.

Do not forget to listen also `close` as a garbage collector.

**Comment by tikagnus** [comment]
Hi @Pierozi.  Thanks for reply. I already tried to serialize/cache Connection Object, but when i try to use, i get this error
```php
 $conn->send('test');
Hoa\Stream\Exception with message 'Try to change the stream resource with an invalid one; given integer.'

```

**Comment by Pierozi** [comment]
`Serialize` ? You (cannot / do not) serialize a php resource or any `stream`

During the time where your WebSocket Server listens to connection, he should handle his pool of clients and theses client keep in a stack like `SplObjectStorage`.

**Comment by tikagnus** [comment]
Hi guys. You can close this issue. I was able to achive what I wanted.
Good job with this library.
